#!/usr/bin/env python3
"""Validate Snakemake's Linux explicit Conda pins without installing them."""

from __future__ import annotations

import argparse
import re
import sys
from collections.abc import Callable
from pathlib import Path
from urllib.parse import unquote, urlsplit

import yaml


PLATFORM = "linux-64"
CHANNELS = ["conda-forge", "bioconda", "nodefaults"]
ROOT_ENVIRONMENTS = ("environment.yaml", "environment-dev.yaml")
VIRTUAL_PACKAGES = {
    "subdirs": {
        PLATFORM: {
            "packages": {
                "__unix": "0",
                "__linux": "3.10",
                "__archspec": "1 x86_64",
                "__glibc": "2.17",
            }
        }
    }
}
HASH = re.compile(r"^[0-9a-f]{64}$")
PACKAGE_HASH = re.compile(r"^(?:[0-9a-f]{32}|[0-9a-f]{64})$")
DEPENDENCY = re.compile(r"^([A-Za-z0-9_.-]+)(?:\s*=\s*([^\s=]+))?$")


class PinError(RuntimeError):
    """A source environment and its explicit pin violate the lock policy."""


def _package_identity(url: str, pin_file: Path) -> tuple[str, str]:
    parsed = urlsplit(url)
    if (
        parsed.scheme != "https"
        or parsed.netloc != "conda.anaconda.org"
        or parsed.username is not None
        or parsed.password is not None
        or parsed.query
        or not PACKAGE_HASH.fullmatch(parsed.fragment)
    ):
        raise PinError(f"{pin_file}: disallowed or malformed package URL: {url}")

    parts = [unquote(part) for part in parsed.path.split("/") if part]
    if len(parts) != 3 or parts[0] not in CHANNELS[:2] or parts[1] not in {
        PLATFORM,
        "noarch",
    } or any("/" in part or "\\" in part for part in parts):
        raise PinError(f"{pin_file}: unexpected channel or platform in {url}")
    filename = parts[2]
    if filename.endswith(".tar.bz2"):
        distribution = filename[: -len(".tar.bz2")]
    elif filename.endswith(".conda"):
        distribution = filename[: -len(".conda")]
    else:
        raise PinError(f"{pin_file}: unsupported package filename: {filename}")
    try:
        name, version, _ = distribution.rsplit("-", 2)
    except ValueError as error:
        raise PinError(f"{pin_file}: malformed package filename: {filename}") from error
    return name.lower(), version


def _parse_pin(pin_file: Path) -> tuple[str, dict[str, set[str]], int]:
    lines = pin_file.read_text(encoding="utf-8").splitlines()
    if len(lines) < 5 or lines[0] != "# Generated by conda-lock.":
        raise PinError(f"{pin_file}: missing conda-lock header or package entries")
    if lines[1] != f"# platform: {PLATFORM}" or lines[3] != "@EXPLICIT":
        raise PinError(f"{pin_file}: not a {PLATFORM} explicit Conda pin")
    prefix = "# input_hash: "
    if not lines[2].startswith(prefix) or not HASH.fullmatch(lines[2][len(prefix) :]):
        raise PinError(f"{pin_file}: missing 64-character input hash")

    packages: dict[str, set[str]] = {}
    for line_number, line in enumerate(lines[4:], 5):
        if not line or line.startswith(("#", "@")):
            raise PinError(f"{pin_file}:{line_number}: unexpected explicit-file line")
        name, version = _package_identity(line, pin_file)
        if name in packages:
            raise PinError(
                f"{pin_file}:{line_number}: duplicate package entry for {name!r}"
            )
        packages[name] = {version}
    return lines[2][len(prefix) :], packages, len(lines) - 4


def _parse_environment(env_file: Path) -> list[tuple[str, str | None]]:
    document = yaml.safe_load(env_file.read_text(encoding="utf-8"))
    if not isinstance(document, dict) or document.get("channels") != CHANNELS:
        raise PinError(
            f"{env_file}: channels must be exactly {CHANNELS!r} in priority order"
        )
    raw_dependencies = document.get("dependencies")
    if not isinstance(raw_dependencies, list) or not raw_dependencies:
        raise PinError(f"{env_file}: dependencies must be a non-empty list")

    dependencies = []
    for raw_dependency in raw_dependencies:
        if not isinstance(raw_dependency, str):
            raise PinError(
                f"{env_file}: explicit Snakemake pins cannot represent pip mappings"
            )
        match = DEPENDENCY.fullmatch(raw_dependency.strip())
        if not match:
            raise PinError(
                f"{env_file}: unsupported dependency constraint {raw_dependency!r}"
            )
        dependencies.append((match.group(1).lower(), match.group(2)))
    return dependencies


def _validate_virtual_packages(virtual_packages: Path) -> None:
    document = yaml.safe_load(virtual_packages.read_text(encoding="utf-8"))
    if document != VIRTUAL_PACKAGES:
        raise PinError(
            f"{virtual_packages}: expected the portable non-CUDA "
            f"{PLATFORM} virtual-package baseline"
        )


def conda_lock_hashes(env_file: Path, virtual_packages: Path) -> set[str]:
    """Compute accepted conda-lock 4.x input hashes without solving packages."""
    try:
        from conda_lock.content_hash import backwards_compatible_content_hashes
        from conda_lock.src_parser import make_lock_spec
        from conda_lock.virtual_package import virtual_package_repo_from_specification
    except ImportError as error:
        raise PinError(
            "conda-lock is required; create the pinned development environment"
        ) from error

    specification = make_lock_spec(
        src_files=[env_file],
        platform_overrides=[PLATFORM],
        mapping_url="",
    )
    virtual_repository = virtual_package_repo_from_specification(virtual_packages)
    with virtual_repository:
        return backwards_compatible_content_hashes(
            specification,
            virtual_repository,
            PLATFORM,
        )


def validate_pin(
    env_file: Path,
    pin_file: Path,
    virtual_packages: Path,
    hash_provider: Callable[[Path, Path], set[str]] = conda_lock_hashes,
) -> int:
    """Validate one content-addressed explicit pin against its direct inputs."""
    input_hash, packages, entry_count = _parse_pin(pin_file)
    expected_hashes = hash_provider(env_file, virtual_packages)
    if input_hash not in expected_hashes:
        raise PinError(
            f"{pin_file}: stale input hash for {env_file.name} or "
            f"{virtual_packages.name}"
        )
    for name, required_version in _parse_environment(env_file):
        versions = packages.get(name, set())
        if not versions:
            raise PinError(f"{pin_file}: direct dependency {name!r} is absent")
        if required_version is not None and not any(
            version == required_version or version.startswith(required_version + ".")
            for version in versions
        ):
            raise PinError(
                f"{pin_file}: {name!r} does not satisfy ={required_version}; "
                f"locked versions are {sorted(versions)!r}"
            )
    return entry_count


def validate_repository(
    repository: Path,
    hash_provider: Callable[[Path, Path], set[str]] = conda_lock_hashes,
) -> tuple[int, int]:
    env_dir = repository / "workflow" / "envs"
    virtual_packages = repository / "workflow" / "conda-lock" / "virtual-packages.yml"
    if not virtual_packages.is_file():
        raise PinError(f"missing virtual-package baseline: {virtual_packages}")
    _validate_virtual_packages(virtual_packages)

    root_environments = [repository / name for name in ROOT_ENVIRONMENTS]
    missing_environments = [path for path in root_environments if not path.is_file()]
    if missing_environments:
        raise PinError(
            "missing top-level Conda environments: "
            f"{[path.name for path in missing_environments]}"
        )
    environments = root_environments + sorted(env_dir.glob("*.yaml"))
    pins = list(repository.glob(f"environment*.{PLATFORM}.pin.txt"))
    pins.extend(env_dir.glob(f"*.{PLATFORM}.pin.txt"))
    expected_pins = {
        env_file.with_suffix(f".{PLATFORM}.pin.txt") for env_file in environments
    }
    actual_pins = set(pins)
    missing = sorted(expected_pins - actual_pins)
    orphaned = sorted(actual_pins - expected_pins)
    if missing or orphaned:
        raise PinError(
            "Conda pin inventory mismatch; missing={}, orphaned={}".format(
                [path.name for path in missing],
                [path.name for path in orphaned],
            )
        )

    package_count = 0
    for env_file in environments:
        pin_file = env_file.with_suffix(f".{PLATFORM}.pin.txt")
        package_count += validate_pin(
            env_file,
            pin_file,
            virtual_packages,
            hash_provider,
        )
    return len(environments), package_count


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repository",
        type=Path,
        default=Path(__file__).resolve().parents[2],
    )
    args = parser.parse_args()
    try:
        environment_count, package_count = validate_repository(
            args.repository.resolve()
        )
    except (OSError, UnicodeError, yaml.YAMLError, PinError) as error:
        print(f"Conda pin validation failed: {error}", file=sys.stderr)
        return 1
    print(
        f"Validated {environment_count} Linux-64 Conda pins "
        f"containing {package_count} exact package builds."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
