"""Structural regression tests for Snakemake's explicit Conda pins."""

import importlib.util
import subprocess
import sys
from pathlib import Path

import pytest


REPO = Path(__file__).resolve().parent.parent
CHECKER_PATH = REPO / ".github" / "scripts" / "check_conda_pins.py"
SPEC = importlib.util.spec_from_file_location("check_conda_pins", CHECKER_PATH)
assert SPEC is not None and SPEC.loader is not None
CHECKER = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(CHECKER)
sys.modules["check_conda_pins"] = CHECKER
UPDATER_PATH = REPO / ".github" / "scripts" / "update_conda_pins.py"
UPDATER_SPEC = importlib.util.spec_from_file_location("update_conda_pins", UPDATER_PATH)
assert UPDATER_SPEC is not None and UPDATER_SPEC.loader is not None
UPDATER = importlib.util.module_from_spec(UPDATER_SPEC)
UPDATER_SPEC.loader.exec_module(UPDATER)

INPUT_HASH = "1" * 64
PACKAGE_HASH = "2" * 32


def write_fixture_repository(tmp_path: Path) -> tuple[Path, Path, Path]:
    env_dir = tmp_path / "workflow" / "envs"
    lock_dir = tmp_path / "workflow" / "conda-lock"
    env_dir.mkdir(parents=True)
    lock_dir.mkdir(parents=True)

    environment_text = (
        "channels:\n"
        "  - conda-forge\n"
        "  - bioconda\n"
        "  - nodefaults\n"
        "dependencies:\n"
        "  - bedtools =2.31.1\n"
    )
    pin_text = (
        "# Generated by conda-lock.\n"
        "# platform: linux-64\n"
        f"# input_hash: {INPUT_HASH}\n"
        "@EXPLICIT\n"
        "https://conda.anaconda.org/bioconda/linux-64/"
        f"bedtools-2.31.1-h123_0.conda#{PACKAGE_HASH}\n"
    )
    for environment in (
        tmp_path / "environment.yaml",
        tmp_path / "environment-dev.yaml",
        env_dir / "example.yaml",
    ):
        environment.write_text(environment_text)
        environment.with_suffix(".linux-64.pin.txt").write_text(pin_text)

    environment = env_dir / "example.yaml"
    pin = env_dir / "example.linux-64.pin.txt"
    virtual_packages = lock_dir / "virtual-packages.yml"
    virtual_packages.write_text(
        "subdirs:\n"
        "  linux-64:\n"
        "    packages:\n"
        '      __unix: "0"\n'
        '      __linux: "3.10"\n'
        '      __archspec: "1 x86_64"\n'
        '      __glibc: "2.17"\n'
    )
    return environment, pin, virtual_packages


def expected_hash(_environment: Path, _virtual_packages: Path) -> set[str]:
    return {INPUT_HASH}


def test_checked_in_conda_pins_have_complete_content_addressed_inventory():
    def recorded_hash(environment: Path, _virtual_packages: Path) -> set[str]:
        pin = environment.with_suffix(".linux-64.pin.txt")
        return {pin.read_text().splitlines()[2].removeprefix("# input_hash: ")}

    assert CHECKER.validate_repository(REPO, recorded_hash)[0] == 23


def test_coverage_environment_declares_mapping_runtime_dependencies():
    dependencies = {
        name
        for name, _version in CHECKER._parse_environment(
            REPO / "workflow" / "envs" / "coverage.yaml"
        )
    }

    assert {"numpy", "pandas", "pysam"} <= dependencies


def test_conda_pin_fixture_is_accepted(tmp_path):
    write_fixture_repository(tmp_path)

    assert CHECKER.validate_repository(tmp_path, expected_hash) == (3, 3)


def test_conda_pin_inventory_must_be_complete(tmp_path):
    _environment, pin, _virtual_packages = write_fixture_repository(tmp_path)
    pin.unlink()

    with pytest.raises(CHECKER.PinError, match="inventory mismatch"):
        CHECKER.validate_repository(tmp_path, expected_hash)


def test_conda_pin_input_hash_must_match_sources(tmp_path):
    write_fixture_repository(tmp_path)

    with pytest.raises(CHECKER.PinError, match="stale input hash"):
        CHECKER.validate_repository(tmp_path, lambda *_args: {"0" * 64})


@pytest.mark.parametrize(
    "replacement",
    [
        "http://conda.anaconda.org/bioconda/linux-64/",
        "https://user@conda.anaconda.org/bioconda/linux-64/",
        "https://repo.anaconda.com/bioconda/linux-64/",
        "https://conda.anaconda.org/defaults/linux-64/",
        "https://conda.anaconda.org/bioconda/osx-64/",
    ],
)
def test_conda_pin_rejects_untrusted_package_locations(tmp_path, replacement):
    _environment, pin, _virtual_packages = write_fixture_repository(tmp_path)
    pin.write_text(
        pin.read_text().replace(
            "https://conda.anaconda.org/bioconda/linux-64/", replacement
        )
    )

    with pytest.raises(CHECKER.PinError, match="disallowed|unexpected"):
        CHECKER.validate_repository(tmp_path, expected_hash)


def test_conda_pin_rejects_duplicate_packages(tmp_path):
    _environment, pin, _virtual_packages = write_fixture_repository(tmp_path)
    package = pin.read_text().splitlines()[-1]
    pin.write_text(pin.read_text() + package.replace("h123_0", "h456_1") + "\n")

    with pytest.raises(CHECKER.PinError, match="duplicate package entry"):
        CHECKER.validate_repository(tmp_path, expected_hash)


@pytest.mark.parametrize(
    ("dependency", "message"),
    [
        ("samtools =1.24", "direct dependency 'samtools' is absent"),
        ("bedtools =2.30.0", "does not satisfy =2.30.0"),
    ],
)
def test_conda_pin_covers_direct_dependencies(
    tmp_path, dependency, message
):
    environment, _pin, _virtual_packages = write_fixture_repository(tmp_path)
    environment.write_text(environment.read_text().replace("bedtools =2.31.1", dependency))

    with pytest.raises(CHECKER.PinError, match=message):
        CHECKER.validate_repository(tmp_path, expected_hash)


def test_conda_environment_requires_closed_channel_set(tmp_path):
    environment, _pin, _virtual_packages = write_fixture_repository(tmp_path)
    environment.write_text(environment.read_text().replace("  - nodefaults\n", ""))

    with pytest.raises(CHECKER.PinError, match="channels must be exactly"):
        CHECKER.validate_repository(tmp_path, expected_hash)


def test_conda_environment_rejects_pip_dependency_mappings(tmp_path):
    environment, _pin, _virtual_packages = write_fixture_repository(tmp_path)
    environment.write_text(
        environment.read_text().replace(
            "  - bedtools =2.31.1\n",
            "  - pip\n  - pip:\n      - arbitrary-package==1.0\n",
        )
    )

    with pytest.raises(CHECKER.PinError, match="cannot represent pip mappings"):
        CHECKER.validate_repository(tmp_path, expected_hash)


def test_virtual_packages_must_fix_os_cpu_and_glibc_baseline(tmp_path):
    _environment, _pin, virtual_packages = write_fixture_repository(tmp_path)
    virtual_packages.write_text(
        virtual_packages.read_text().replace('      __archspec: "1 x86_64"\n', "")
    )

    with pytest.raises(CHECKER.PinError, match="portable non-CUDA"):
        CHECKER.validate_repository(tmp_path, expected_hash)


def test_regeneration_validates_every_staged_pin_before_publication(
    tmp_path, monkeypatch
):
    _environment, original_pin, _virtual_packages = write_fixture_repository(tmp_path)
    original_contents = original_pin.read_text()
    commands = []

    def fake_run(command, **kwargs):
        commands.append((command, kwargs))
        if command[1:] == ["--version"]:
            return subprocess.CompletedProcess(
                command,
                0,
                stdout="conda-lock, version 4.0.2\n",
            )

        template = Path(command[command.index("--filename-template") + 1])
        rendered = Path(str(template).replace("{platform}", "linux-64"))
        rendered.write_text(
            original_contents.replace(
                "https://conda.anaconda.org/",
                "https://user@conda.anaconda.org/",
            )
        )
        return subprocess.CompletedProcess(command, 0)

    monkeypatch.setattr(UPDATER.subprocess, "run", fake_run)

    with pytest.raises(CHECKER.PinError, match="disallowed or malformed"):
        UPDATER.regenerate(
            tmp_path,
            Path("/tools/conda-lock"),
            Path("/tools/mamba"),
            expected_hash,
        )

    assert original_pin.read_text() == original_contents
    lock_command, lock_options = commands[1]
    assert "--strip-auth" in lock_command
    assert lock_options["env"]["CONDA_CHANNEL_PRIORITY"] == "strict"
