#Taxonomy of the samples to be processed, in this case Bacteria
taxonomy: "Bacteria"
#Adapter sequence used
adapter: ""
samples: "SPtools/samples.tsv"
genomeindexpath: ""
alternativestartcodons: "GTG,TTG"
#TISHMODE: RIBOONLY for only riboseq (Chloramphenicol treatment), TISONLY for only tis(retapalmuline, tetracycline), ALL for both 
tishmode: "RIBOONLY"
